
import NavBar from "./components/navBar";
import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";

const geist = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "700"], 
});
export const metadata = {
  title: "SKIILINK | Nigeria",
  description: "Generated by create next app",
};
export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geist.className} bg-[#fafafa] text-black selection:bg-teal-30`}
      >
        
        {/* <NavBar />
        <main className="w-full flex flex-col items-start justify-center">
          {children}
        </main> */}
        
      </body>
    </html>
  );
} 


