import NavBar from "./components/navBar";
import "./globals.css";
import { DM_Sans } from "next/font/google";

const geist = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], 
});
export const metadata = {
  title: "SKIILINK Store | Nigeria",
  description: "Generated by create next app",
};
export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geist.className} bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white`}
      >
        <NavBar />
        <main className="w-full flex flex-col items-start justify-center">
          {children}
        </main>
        
      </body>
    </html>
  );
}
